// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ErpNextPocTests.InfoSupports
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class 查詢進度_提案人Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "查詢進度_提案人.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "查詢進度_提案人", "\tIn order to 追蹤服務單進度\r\n\tAs a 提案人\r\n\tI want to 可對資訊服務單進度進行查詢", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "查詢進度_提案人")))
            {
                ErpNextPocTests.InfoSupports.查詢進度_提案人Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void 依據所輸入的查詢條件查詢資料(string beginDocno, string endDocno, string dpt, string state, string beginDocdate, string endDocdate, string beginEST_Cmplt_Date, string endEST_Cmplt_Date, string approve_State, string approveMyself, string noFinsh, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag",
                    "目前條件共有:單號區間、模組(下拉)、申請事業部(下拉)、申請部門(下拉)、單據狀態(勾選-可複選)、",
                    "申請日期區間、核準日期區間、實際完成日日期區間、預計完成日日期區間、驗收日期區間、發票日期區間、",
                    "簽核狀態(勾選-可複選)、簽核(勾選)、未結案月份(勾選-單選)、資訊組主管是否已會簽申請(下拉)",
                    "共22個條件",
                    "提案人需用到的條件",
                    "單號區間、申請部門、單據狀態(勾選)、申請日期區間、預計完成日區間、簽核狀態(勾選)、簽核(勾選)、未結案狀態(選取)",
                    "使用outline方式查詢"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("依據所輸入的查詢條件查詢資料", @__tags);
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given(string.Format("單號區間(起)條件輸入{0}", beginDocno), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 19
 testRunner.And(string.Format("單號區間(迄)條件輸入{0}", endDocno), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
 testRunner.And(string.Format("申請部門條件選取{0}", dpt), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.And(string.Format("單據狀態條件勾選{0}", state), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.And(string.Format("申請日期區間(起日)條件輸入{0}", beginDocdate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And(string.Format("申請日期區間(迄日)條件輸入{0}", endDocdate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And(string.Format("預計完成日日期區間(起日)條件輸入{0}", beginEST_Cmplt_Date), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And(string.Format("預計完成日日期區間(迄日)條件輸入{0}", endEST_Cmplt_Date), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And(string.Format("簽核狀態條件勾選{0}", approve_State), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And(string.Format("簽核條件勾選{0}", approveMyself), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And(string.Format("未結案狀態條件選取{0}", noFinsh), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.When("按下查詢按鈕", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("\"有正確收到查詢條件\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("依據所輸入的查詢條件查詢資料: 2016070001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "查詢進度_提案人")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("目前條件共有:單號區間、模組(下拉)、申請事業部(下拉)、申請部門(下拉)、單據狀態(勾選-可複選)、")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("申請日期區間、核準日期區間、實際完成日日期區間、預計完成日日期區間、驗收日期區間、發票日期區間、")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("簽核狀態(勾選-可複選)、簽核(勾選)、未結案月份(勾選-單選)、資訊組主管是否已會簽申請(下拉)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("共22個條件")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("提案人需用到的條件")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("單號區間、申請部門、單據狀態(勾選)、申請日期區間、預計完成日區間、簽核狀態(勾選)、簽核(勾選)、未結案狀態(選取)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("使用outline方式查詢")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "單一查詢條件")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "2016070001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BeginDocno", "2016070001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EndDocno", "2016070099")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Dpt", "VR11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:State", "3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BeginDocdate", "20160701")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EndDocdate", "20160731")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BeginEST_cmplt_Date", "20160701")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EndEST_cmplt_Date", "20160731")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Approve_state", "3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ApproveMyself", "true")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NoFinsh", "3")]
        public virtual void 依據所輸入的查詢條件查詢資料_單一查詢條件_2016070001()
        {
            this.依據所輸入的查詢條件查詢資料("2016070001", "2016070099", "VR11", "3", "20160701", "20160731", "20160701", "20160731", "3", "true", "3", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
