// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ErpNextPocTests.InfoSupports
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class 查詢進度_提案人Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "查詢進度_提案人.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "查詢進度_提案人", "\tIn order to 追蹤服務單進度\r\n\tAs a 提案人\r\n\tI want to 可對資訊服務單進度進行查詢", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "查詢進度_提案人")))
            {
                ErpNextPocTests.InfoSupports.查詢進度_提案人Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("查詢申請日期起訖日")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "查詢進度_提案人")]
        public virtual void 查詢申請日期起訖日()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("查詢申請日期起訖日", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "BeginDocno",
                        "EndDocno",
                        "Dpt",
                        "State",
                        "BeginDocdate",
                        "EndDocdate",
                        "BeginEST_cmplt_Date",
                        "EndEST_cmplt_Date",
                        "Approve_state",
                        "ApproveMyself",
                        "NoFinsh"});
            table1.AddRow(new string[] {
                        "2016070001",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table1.AddRow(new string[] {
                        "2016070002",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table1.AddRow(new string[] {
                        "2016070003",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table1.AddRow(new string[] {
                        "2016070004",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
#line 7
 testRunner.Given("資料庫有服務單", ((string)(null)), table1, "Given ");
#line 13
 testRunner.When("申請日期區間(起日)條件輸入\"2016070001\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
 testRunner.And("申請日期區間(迄日)條件輸入\"2016070002\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And("呼叫查詢方法", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "BeginDocno",
                        "EndDocno",
                        "Dpt",
                        "State",
                        "BeginDocdate",
                        "EndDocdate",
                        "BeginEST_cmplt_Date",
                        "EndEST_cmplt_Date",
                        "Approve_state",
                        "ApproveMyself",
                        "NoFinsh"});
            table2.AddRow(new string[] {
                        "2016070001",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table2.AddRow(new string[] {
                        "2016070002",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
#line 16
 testRunner.Then("搜尋結果為", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("查詢預計完成日日期起訖日")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "查詢進度_提案人")]
        public virtual void 查詢預計完成日日期起訖日()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("查詢預計完成日日期起訖日", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "BeginDocno",
                        "EndDocno",
                        "Dpt",
                        "State",
                        "BeginDocdate",
                        "EndDocdate",
                        "BeginEST_cmplt_Date",
                        "EndEST_cmplt_Date",
                        "Approve_state",
                        "ApproveMyself",
                        "NoFinsh"});
            table3.AddRow(new string[] {
                        "2016070001",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table3.AddRow(new string[] {
                        "2016070002",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table3.AddRow(new string[] {
                        "2016070003",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table3.AddRow(new string[] {
                        "2016070004",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
#line 22
 testRunner.Given("資料庫有服務單", ((string)(null)), table3, "Given ");
#line 28
 testRunner.When("預計完成日日期區間(起日)條件輸入\"2016070001\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
 testRunner.And("預計完成日日期區間(迄日)條件輸入\"2016070002\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("呼叫查詢方法", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "BeginDocno",
                        "EndDocno",
                        "Dpt",
                        "State",
                        "BeginDocdate",
                        "EndDocdate",
                        "BeginEST_cmplt_Date",
                        "EndEST_cmplt_Date",
                        "Approve_state",
                        "ApproveMyself",
                        "NoFinsh"});
            table4.AddRow(new string[] {
                        "2016070001",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table4.AddRow(new string[] {
                        "2016070002",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
#line 31
 testRunner.Then("搜尋結果為", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("查詢單號區間(迄)起訖")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "查詢進度_提案人")]
        public virtual void 查詢單號區間迄起訖()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("查詢單號區間(迄)起訖", ((string[])(null)));
#line 36
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "BeginDocno",
                        "EndDocno",
                        "Dpt",
                        "State",
                        "BeginDocdate",
                        "EndDocdate",
                        "BeginEST_cmplt_Date",
                        "EndEST_cmplt_Date",
                        "Approve_state",
                        "ApproveMyself",
                        "NoFinsh"});
            table5.AddRow(new string[] {
                        "2016070001",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table5.AddRow(new string[] {
                        "2016070002",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table5.AddRow(new string[] {
                        "2016070003",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table5.AddRow(new string[] {
                        "2016070004",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
#line 37
 testRunner.Given("資料庫有服務單", ((string)(null)), table5, "Given ");
#line 43
 testRunner.When("單號區間條件輸入\"2016070001\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 44
 testRunner.And("呼叫查詢方法", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "BeginDocno",
                        "EndDocno",
                        "Dpt",
                        "State",
                        "BeginDocdate",
                        "EndDocdate",
                        "BeginEST_cmplt_Date",
                        "EndEST_cmplt_Date",
                        "Approve_state",
                        "ApproveMyself",
                        "NoFinsh"});
            table6.AddRow(new string[] {
                        "2016070001",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table6.AddRow(new string[] {
                        "2016070002",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
#line 45
 testRunner.Then("搜尋結果為", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("查詢單據狀態")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "查詢進度_提案人")]
        public virtual void 查詢單據狀態()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("查詢單據狀態", ((string[])(null)));
#line 51
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "BeginDocno",
                        "EndDocno",
                        "Dpt",
                        "State",
                        "BeginDocdate",
                        "EndDocdate",
                        "BeginEST_cmplt_Date",
                        "EndEST_cmplt_Date",
                        "Approve_state",
                        "ApproveMyself",
                        "NoFinsh"});
            table7.AddRow(new string[] {
                        "2016070001",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table7.AddRow(new string[] {
                        "2016070002",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table7.AddRow(new string[] {
                        "2016070003",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table7.AddRow(new string[] {
                        "2016070004",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
#line 52
 testRunner.Given("資料庫有服務單", ((string)(null)), table7, "Given ");
#line 58
 testRunner.When("單據狀態條件勾選3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
 testRunner.And("簽核狀態條件勾選3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.And("未結案狀態條件選取3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
 testRunner.And("呼叫查詢方法", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "BeginDocno",
                        "EndDocno",
                        "Dpt",
                        "State",
                        "BeginDocdate",
                        "EndDocdate",
                        "BeginEST_cmplt_Date",
                        "EndEST_cmplt_Date",
                        "Approve_state",
                        "ApproveMyself",
                        "NoFinsh"});
            table8.AddRow(new string[] {
                        "2016070001",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
#line 62
 testRunner.Then("搜尋結果為", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("查詢自身簽核單據")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "查詢進度_提案人")]
        public virtual void 查詢自身簽核單據()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("查詢自身簽核單據", ((string[])(null)));
#line 66
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "BeginDocno",
                        "EndDocno",
                        "Dpt",
                        "State",
                        "BeginDocdate",
                        "EndDocdate",
                        "BeginEST_cmplt_Date",
                        "EndEST_cmplt_Date",
                        "Approve_state",
                        "ApproveMyself",
                        "NoFinsh"});
            table9.AddRow(new string[] {
                        "2016070001",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "false",
                        "3"});
            table9.AddRow(new string[] {
                        "2016070002",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "false",
                        "3"});
            table9.AddRow(new string[] {
                        "2016070003",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "false",
                        "3"});
            table9.AddRow(new string[] {
                        "2016070004",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
#line 67
 testRunner.Given("資料庫有服務單", ((string)(null)), table9, "Given ");
#line 73
 testRunner.When("簽核條件勾選\"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 74
 testRunner.And("呼叫查詢方法", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "BeginDocno",
                        "EndDocno",
                        "Dpt",
                        "State",
                        "BeginDocdate",
                        "EndDocdate",
                        "BeginEST_cmplt_Date",
                        "EndEST_cmplt_Date",
                        "Approve_state",
                        "ApproveMyself",
                        "NoFinsh"});
            table10.AddRow(new string[] {
                        "2016070001",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
#line 75
 testRunner.Then("搜尋結果為", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("查詢單據部門")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "查詢進度_提案人")]
        public virtual void 查詢單據部門()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("查詢單據部門", ((string[])(null)));
#line 79
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "BeginDocno",
                        "EndDocno",
                        "Dpt",
                        "State",
                        "BeginDocdate",
                        "EndDocdate",
                        "BeginEST_cmplt_Date",
                        "EndEST_cmplt_Date",
                        "Approve_state",
                        "ApproveMyself",
                        "NoFinsh"});
            table11.AddRow(new string[] {
                        "2016070001",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table11.AddRow(new string[] {
                        "2016070002",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table11.AddRow(new string[] {
                        "2016070003",
                        "2016070099",
                        "VR12",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table11.AddRow(new string[] {
                        "2016070004",
                        "2016070099",
                        "VR12",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
#line 80
 testRunner.Given("資料庫有服務單", ((string)(null)), table11, "Given ");
#line 86
 testRunner.When("申請部門條件選取\"VR11\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 87
 testRunner.And("呼叫查詢方法", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "BeginDocno",
                        "EndDocno",
                        "Dpt",
                        "State",
                        "BeginDocdate",
                        "EndDocdate",
                        "BeginEST_cmplt_Date",
                        "EndEST_cmplt_Date",
                        "Approve_state",
                        "ApproveMyself",
                        "NoFinsh"});
            table12.AddRow(new string[] {
                        "2016070001",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
            table12.AddRow(new string[] {
                        "2016070002",
                        "2016070099",
                        "VR11",
                        "3",
                        "20160701",
                        "20160731",
                        "20160701",
                        "20160731",
                        "3",
                        "true",
                        "3"});
#line 88
 testRunner.Then("搜尋結果為", ((string)(null)), table12, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
